trigger:
  - main

variables:
  dockerRegistryServiceConnection: 'myACR'
  imageRepository: 'redis'
  containerRegistry: 'crry6vhgxwxv45m.azurecr.io'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'imagepullsecret'

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build job
        pool:
          name: selfhostedpool
          demands:
          - agent.name -equals shubuntu
        steps:

          - task: Docker@2
            displayName: Pull redis image
            inputs:
              command: pull
              arguments: redis:latest

          - task: Docker@2
            displayName: Build Docker image
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(imageRepository)'
              command: 'build'
              dockerfilePath: 'Dockerfile'
              buildContext: '**'
              tags: latest

          - task: Docker@2
            displayName: Push image to ACR
            inputs:
              command: push
              repository: $(imageRepository)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: latest

  - stage: Deploy
    displayName: Deploy to AKS
    jobs:
      - deployment: Deploy
        displayName: Deploy job
        pool:
          name: selfhostedpool
          demands:
          - agent.name -equals shubuntu
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: KubernetesManifest@0
                  displayName: Create imagePullSecret
                  inputs:
                    action: 'createSecret'
                    kubernetesServiceConnection: 'myaks'
                    namespace: 'default'
                    secretType: 'dockerRegistry'
                    secretName: '$(imagePullSecret)'
                    dockerRegistryEndpoint: '$(dockerRegistryServiceConnection)'
                    
                - task: KubernetesManifest@0
                  displayName: Deploy to AKS
                  inputs:
                    action: 'deploy'
                    kubernetesServiceConnection: 'myaks'
                    namespace: 'default'
                    manifests: testing.yml