resources:
  repositories:
    - repository: self
      trigger: none

stages:
- stage: PreCheck
  displayName: Kubernetes Check
  jobs:
  - job: Build
    pool:
      name: selfhostedpool
      demands:
      - agent.name -equals shubuntu
    steps:
    - task: Kubernetes@1
      displayName: 'Validate testing.yml'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        namespace: 'default'
        command: 'apply'
        arguments: '--dry-run=client --validate -f $(System.DefaultWorkingDirectory)/testing.yml'