trigger:
- main

variables:
  azureServiceConnection: 'MyAzureServiceConnection'
  resourceGroup: 'RG2a'
  appServiceName: 'WebAppRG2a'
  storageAccountName: 'StorageAccountRG2a'
  environmentName: 'production'
  functionAppName: 'FuncAppRG2a'
  location: 'westeurope'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '5.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        echo "Listing files in the current directory:"
        ls -la
      displayName: 'List Files in Build Directory'

    - script: |
        for d in */ ; do
          if [ -f "$d/project.json" ]; then
            echo "Building project in directory $d"
            dotnet build "$d" --configuration Release
          fi
        done
      displayName: 'Build Projects'

    - script: |
        echo "##vso[task.setvariable variable=BuildConfiguration]Release"
      displayName: 'Set Build Configuration Variable'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy Job'
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploying to Azure App Service"
            displayName: 'Deploy Script'
            
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appType: 'webApp'
              appName: '$(appServiceName)'
              package: '$(Build.ArtifactStagingDirectory)/*.zip'
              deploymentMethod: 'auto'
            displayName: 'Azure Web App Deploy'
            condition: eq(variables['BuildConfiguration'], 'Release')

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage account show -n $(storageAccountName) -g $(resourceGroup)
            displayName: 'Check Storage Account'
            condition: eq(variables['BuildConfiguration'], 'Release')

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Create the resource group if it doesn't exist
                az group create --name $(resourceGroup) --location $(location)

                # Create the storage account if it doesn't exist
                az storage account create --name $(storageAccountName) --location $(location) --resource-group $(resourceGroup) --sku Standard_LRS

                # Create the function app if it doesn't exist
                az functionapp create --resource-group $(resourceGroup) --consumption-plan-location $(location) --runtime dotnet --functions-version 3 --name $(functionAppName) --storage-account $(storageAccountName)
            displayName: 'Create Azure Function App'
            condition: eq(variables['BuildConfiguration'], 'Release')

- stage: ManualApproval
  displayName: 'Manual Approval Stage'
  dependsOn: Deploy
  jobs:
  - job: ApprovalJob
    displayName: 'Manual Approval Job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Manual approval required."
      displayName: 'Manual Approval Script'

- stage: PostApproval
  displayName: 'Post Approval Stage'
  dependsOn: ManualApproval
  condition: succeeded()
  jobs:
  - job: PostApprovalJob
    displayName: 'Post Approval Job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Deployment approved, proceeding with post-approval steps."
      displayName: 'Post-Approval Script'

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: $(azureServiceConnection)
        appType: 'functionApp'
        appName: $(functionAppName)
        package: $(Build.ArtifactStagingDirectory)/*.zip
      displayName: 'Deploy to Azure Function App'
