trigger:
- main  # Trigger the pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the build agent

variables:
  azureServiceConnection: 'MyAzureServiceConnection'
  resourceGroup: 'myResourceGroup'
  location: 'eastus'
  sqlServerName: 'mysqlserver213'
  sqlDatabaseName: 'mydatabase213'
  sqlAdminUser: 'sqladmin213'
  sqlAdminPassword: '12345Pass!'
  appServicePlan: 'asp-213a'
  appServiceName: 'app-service-213a'
  firewallRuleName: MyFWRule

stages:
- stage: InfrastructureSetup
  displayName: 'Setup Infrastructure'
  jobs:
  - job: CreateResources
    displayName: 'Create Azure Resources'
    steps:
    - task: AzureCLI@2
      displayName: 'Create Resource Group'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az group create --name $(resourceGroup) --location $(location)
          # Create a resource group in the specified location
    
    - task: AzureCLI@2
      displayName: 'Create SQL Server'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az sql server create --name $(sqlServerName) --resource-group $(resourceGroup) --location $(location) --admin-user $(sqlAdminUser) --admin-password $(sqlAdminPassword)
          # Create an Azure SQL server with the specified admin user and password

    - task: AzureCLI@2
      displayName: 'Create SQL Database'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az sql db create --resource-group $(resourceGroup) --server $(sqlServerName) --name $(sqlDatabaseName) --service-objective S0
          # Create a SQL database on the server with the S0 service objective

- stage: DatabaseMigrations
  displayName: 'Perform Database Migrations'
  dependsOn: InfrastructureSetup
  jobs:
  - job: MigrateDatabase
    displayName: 'Run Database Migrations'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          MY_IP=$(curl -s http://ipinfo.io/json | jq -r '.ip')
          echo "My IP is $MY_IP"
          az sql server firewall-rule create --resource-group $(resourceGroup) --server $(sqlServerName) --name $(firewallRuleName) --start-ip-address $MY_IP --end-ip-address $MY_IP
          # Add the current IP to the SQL server firewall rules to allow access for migrations

    - script: |
        wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.4.2/flyway-commandline-8.4.2-linux-x64.tar.gz | tar xvz
        sudo ln -s $(pwd)/flyway-8.4.2/flyway /usr/local/bin/flyway
      displayName: 'Install Flyway CLI'
      # Download and install Flyway CLI for running database migrations

    - script: |
        flyway -url=${FLYWAY_URL} -user=${FLYWAY_USER} -password=${FLYWAY_PASSWORD} -locations=filesystem:sql migrate
      displayName: 'Run Flyway Migrations'
      env:
        FLYWAY_URL: "jdbc:sqlserver://$(sqlServerName).database.windows.net:1433;databaseName=$(sqlDatabaseName)"
        FLYWAY_USER: "$(sqlAdminUser)"
        FLYWAY_PASSWORD: "$(sqlAdminPassword)"
      # Run Flyway migrations using the specified database connection details

- stage: DeployApp
  displayName: 'Deploy Application'
  dependsOn: DatabaseMigrations
  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure App Service'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet
      # Install the .NET SDK version 8.0.x

    - task: DotNetCoreCLI@2
      displayName: 'Restore .NET Core Packages'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
      # Restore .NET Core project dependencies

    - task: DotNetCoreCLI@2
      displayName: 'Build .NET Core Project'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration Release'
      # Build the .NET Core project in Release configuration

    - task: DotNetCoreCLI@2
      displayName: 'Publish .NET Core Project'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      # Publish the .NET Core project to the artifact staging directory

    - task: AzureCLI@2
      condition: Eq(1,0)
      displayName: 'Create App Service Plan'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az appservice plan create --name $(appServicePlan) --resource-group $(resourceGroup) --location $(location) --sku B1
      # Create an App Service Plan (this step is currently disabled with Eq(1,0) condition)

    - task: AzureCLI@2
      condition: Eq(1,0)
      displayName: 'Create App Service'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az webapp create --name $(appServiceName) --plan $(appServicePlan) --resource-group $(resourceGroup)
      # Create an App Service (this step is currently disabled with Eq(1,0) condition)

    - task: ArchiveFiles@2
      condition: Eq(1,0)
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(appServiceName).zip'
        replaceExistingArchive: true
      # Archive the published project files into a zip file

    - task: AzureWebApp@1
      condition: Eq(1,0)
      displayName: 'Deploy to Azure Web App'
      inputs:
        azureSubscription: $(azureServiceConnection)
        appType: 'webApp'
        appName: '$(appServiceName)'
        package: '$(Build.ArtifactStagingDirectory)/$(appServiceName).zip'
      # Deploy the application zip package to the Azure Web App (this step is currently disabled with Eq(1,0) condition)