trigger:
- main

variables:
  azureServiceConnection: 'MyAzureServiceConnection'
  resourceGroup: 'RG2a'
  appServiceName: 'WebAppRG2a'
  storageAccountName: 'StorageAccountRG2a'
  environmentName: 'production'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '5.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: |
        dotnet build --configuration Release
      displayName: 'Build Project'

    - script: |
        echo "##vso[task.setvariable variable=BuildConfiguration]Release"
      displayName: 'Set Build Configuration Variable'

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    displayName: 'Deploy Job'
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Deploying to Azure App Service"
            displayName: 'Deploy Script'
            
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureServiceConnection)
              appName: $(appServiceName)
              package: $(Build.ArtifactStagingDirectory)/*.zip
            displayName: 'Azure Web App Deploy'
            condition: eq(variables['BuildConfiguration'], 'Release')

          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage account show -n $(storageAccountName) -g $(resourceGroup)
            displayName: 'Check Storage Account'
            condition: eq(variables['BuildConfiguration'], 'Release')

- stage: PostApproval
  displayName: 'Post Approval Stage'
  dependsOn: Deploy
  condition: succeeded()
  jobs:
  - job: PostApprovalJob
    displayName: 'Post Approval Job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: echo "Deployment approved, proceeding with post-approval steps."
      displayName: 'Post-Approval Script'

    - task: AzureFunctionApp@1
      inputs:
        azureSubscription: $(azureServiceConnection)
        appType: 'functionApp'
        appName: 'your-function-app-name'
        package: $(Build.ArtifactStagingDirectory)/*.zip
      displayName: 'Deploy to Azure Function App'
